version: '3'

services:
  portainer:
    image: portainer/portainer-ee:2.20.3
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    network_mode: "bridge"

volumes:
  portainer_data:
