version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mysql_data:/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: "bridge"

volumes:
  mysql_data: